/**
 * @fileoverview gRPC-Web generated client stub for server.generated
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: report.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.server = {};
proto.server.generated = require('./report_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.generated.ReportServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.generated.ReportServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.generated.ManagerRequest,
 *   !proto.server.generated.HTMLResponse>}
 */
const methodDescriptor_ReportService_GetManagerHTML = new grpc.web.MethodDescriptor(
  '/server.generated.ReportService/GetManagerHTML',
  grpc.web.MethodType.UNARY,
  proto.server.generated.ManagerRequest,
  proto.server.generated.HTMLResponse,
  /**
   * @param {!proto.server.generated.ManagerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.generated.HTMLResponse.deserializeBinary
);


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.generated.HTMLResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.generated.HTMLResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.generated.ReportServiceClient.prototype.getManagerHTML =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.generated.ReportService/GetManagerHTML',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetManagerHTML,
      callback);
};


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.generated.HTMLResponse>}
 *     Promise that resolves to the response
 */
proto.server.generated.ReportServicePromiseClient.prototype.getManagerHTML =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.generated.ReportService/GetManagerHTML',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetManagerHTML);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.generated.ManagerRequest,
 *   !proto.server.generated.PDFResponse>}
 */
const methodDescriptor_ReportService_GetManagerPDF = new grpc.web.MethodDescriptor(
  '/server.generated.ReportService/GetManagerPDF',
  grpc.web.MethodType.UNARY,
  proto.server.generated.ManagerRequest,
  proto.server.generated.PDFResponse,
  /**
   * @param {!proto.server.generated.ManagerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.generated.PDFResponse.deserializeBinary
);


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.generated.PDFResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.generated.PDFResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.generated.ReportServiceClient.prototype.getManagerPDF =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.generated.ReportService/GetManagerPDF',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetManagerPDF,
      callback);
};


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.generated.PDFResponse>}
 *     Promise that resolves to the response
 */
proto.server.generated.ReportServicePromiseClient.prototype.getManagerPDF =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.generated.ReportService/GetManagerPDF',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetManagerPDF);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.generated.ManagerRequest,
 *   !proto.server.generated.AllReportsResponse>}
 */
const methodDescriptor_ReportService_GetAllReportsOfManager = new grpc.web.MethodDescriptor(
  '/server.generated.ReportService/GetAllReportsOfManager',
  grpc.web.MethodType.UNARY,
  proto.server.generated.ManagerRequest,
  proto.server.generated.AllReportsResponse,
  /**
   * @param {!proto.server.generated.ManagerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.generated.AllReportsResponse.deserializeBinary
);


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.generated.AllReportsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.generated.AllReportsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.generated.ReportServiceClient.prototype.getAllReportsOfManager =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.generated.ReportService/GetAllReportsOfManager',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetAllReportsOfManager,
      callback);
};


/**
 * @param {!proto.server.generated.ManagerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.generated.AllReportsResponse>}
 *     Promise that resolves to the response
 */
proto.server.generated.ReportServicePromiseClient.prototype.getAllReportsOfManager =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.generated.ReportService/GetAllReportsOfManager',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetAllReportsOfManager);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.generated.EmptyRequest,
 *   !proto.server.generated.AllReportsResponse>}
 */
const methodDescriptor_ReportService_GetAllManagerReports = new grpc.web.MethodDescriptor(
  '/server.generated.ReportService/GetAllManagerReports',
  grpc.web.MethodType.UNARY,
  proto.server.generated.EmptyRequest,
  proto.server.generated.AllReportsResponse,
  /**
   * @param {!proto.server.generated.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.generated.AllReportsResponse.deserializeBinary
);


/**
 * @param {!proto.server.generated.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.generated.AllReportsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.generated.AllReportsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.generated.ReportServiceClient.prototype.getAllManagerReports =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.generated.ReportService/GetAllManagerReports',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetAllManagerReports,
      callback);
};


/**
 * @param {!proto.server.generated.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.generated.AllReportsResponse>}
 *     Promise that resolves to the response
 */
proto.server.generated.ReportServicePromiseClient.prototype.getAllManagerReports =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.generated.ReportService/GetAllManagerReports',
      request,
      metadata || {},
      methodDescriptor_ReportService_GetAllManagerReports);
};


module.exports = proto.server.generated;

